// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqq1Pl3uu2rfmHAFRA2joEONuiQei9PY',
    appId: '1:819014438238:web:974a0cb252012cf66293cf',
    messagingSenderId: '819014438238',
    projectId: 'recipe-maker-9c7a0',
    authDomain: 'recipe-maker-9c7a0.firebaseapp.com',
    storageBucket: 'recipe-maker-9c7a0.firebasestorage.app',
    measurementId: 'G-P0HXZ5PP85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlCl982nv_j0dw07Xpr4hBTj41YUvUTQ',
    appId: '1:819014438238:android:f138fcfcda2393d66293cf',
    messagingSenderId: '819014438238',
    projectId: 'recipe-maker-9c7a0',
    storageBucket: 'recipe-maker-9c7a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfw3wZ0gpaJ52PynWh_z3rj3WqXR7VKkI',
    appId: '1:819014438238:ios:f5168b4a9c5e2d536293cf',
    messagingSenderId: '819014438238',
    projectId: 'recipe-maker-9c7a0',
    storageBucket: 'recipe-maker-9c7a0.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfw3wZ0gpaJ52PynWh_z3rj3WqXR7VKkI',
    appId: '1:819014438238:ios:f5168b4a9c5e2d536293cf',
    messagingSenderId: '819014438238',
    projectId: 'recipe-maker-9c7a0',
    storageBucket: 'recipe-maker-9c7a0.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqq1Pl3uu2rfmHAFRA2joEONuiQei9PY',
    appId: '1:819014438238:web:dad7bea61210e44e6293cf',
    messagingSenderId: '819014438238',
    projectId: 'recipe-maker-9c7a0',
    authDomain: 'recipe-maker-9c7a0.firebaseapp.com',
    storageBucket: 'recipe-maker-9c7a0.firebasestorage.app',
    measurementId: 'G-LEX5JRXZLV',
  );

}