name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      # Debug Step - Show initial environment
      - name: Debug Environment
        run: |
          Write-Host "Initial PATH: $env:Path"
          Write-Host "Current Location: $PWD"
          Write-Host "Windows Version:"
          Get-ComputerInfo | Select-Object WindowsVersion

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      # Verify Flutter is in PATH
      - name: Verify Flutter Installation
        run: |
          $flutterPath = Get-Command flutter -ErrorAction SilentlyContinue
          if ($flutterPath) {
              Write-Host "Flutter found at: $($flutterPath.Source)"
          } else {
              Write-Host "Flutter not found in PATH"
              Write-Host "Current PATH: $env:Path"
              exit 1
          }
          flutter --version
          flutter doctor

      # Install dependencies
      - name: Install Dependencies
        run: |
          flutter pub get
          flutter config --enable-web

      # Build web
      - name: Build Web
        run: |
          $env:Path = "$env:FLUTTER_ROOT\bin;$env:Path"
          Write-Host "Building from directory: $PWD"
          Write-Host "Using Flutter from: $env:FLUTTER_ROOT\bin"
          flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
          channelId: preview
