name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug initial state
      - name: Debug Pre-Flutter
        run: |
          echo "Initial state:"
          echo "PWD: $(pwd)"
          echo "PATH: $PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      # Setup Flutter using full path specification
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      # Export Flutter path and verify installation
      - name: Export Flutter Path
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          source ~/.bashrc || true
          which flutter || echo "Flutter not found in PATH"
          flutter --version || echo "Flutter version failed"

      # Install dependencies with explicit path
      - name: Install Dependencies
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          flutter pub get
          flutter config --enable-web

      # Build web with explicit path
      - name: Build Web
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          echo "Current PATH: $PATH"
          echo "Flutter location: $(which flutter)"
          flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
          channelId: preview
