name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install latest stable Flutter (which includes Dart >= 3.1.4)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'  # Ensure Dart 3.1.4+ is included
          channel: 'stable'

      # Verify the installed Flutter and Dart versions
      - run: flutter --version

      # Enable web support if necessary
      - run: flutter config --enable-web

      # Clean old builds (optional, helps with dependency issues)
      - run: flutter clean

      # Install dependencies
      - run: flutter pub get

      # Build the web app
      - run: flutter build web

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          channelId: live
          projectId: recipe-maker-9c7a0
