name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Pre-Flutter
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "PATH: $PATH"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Debug Post-Flutter Setup
        run: |
          echo "PATH after Flutter setup: $PATH"
          echo "Looking for Flutter:"
          which flutter || echo "Flutter not in PATH"
          echo "Flutter location contents:"
          ls -la $(dirname $(which flutter 2>/dev/null)) || echo "Cannot list Flutter directory"

      - name: Install dependencies
        run: |
          echo "Running pub get from: $(pwd)"
          flutter pub get || echo "pub get failed"

      - name: Enable web
        run: |
          echo "Enabling web support"
          flutter config --enable-web || echo "web enable failed"

      - name: Build web
        run: |
          echo "Starting web build"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          flutter build web || echo "web build failed"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
