name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      # Debug steps to verify Flutter installation
      - name: Debug - Print PATH
        run: echo $PATH
        
      - name: Debug - List Flutter directory
        run: |
          ls -la $GITHUB_WORKSPACE
          which flutter || echo "Flutter not in PATH"
          
      - name: Verify Flutter installation
        run: |
          flutter --version || echo "Flutter command failed"
          flutter doctor -v || echo "Flutter doctor failed"

      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Build web
        run: |
          pwd
          echo "Current directory contents:"
          ls -la
          flutter build web
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
