name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Java for Windows
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter with Windows-specific configuration
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      # Verify Flutter installation
      - name: Verify Flutter
        run: |
          flutter --version
          flutter doctor
        shell: pwsh

      # Install dependencies and enable web
      - name: Setup Flutter project
        run: |
          flutter pub get
          flutter config --enable-web
        shell: pwsh

      # Build for web
      - name: Build web
        run: flutter build web
        shell: pwsh

      # Deploy to Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
          channelId: preview
