name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Flutter SDK with the required Dart version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Choose a version that supports Dart SDK >=3.1.4

      # Check if Flutter and Dart SDK are set up properly
      - run: flutter doctor

      # Install dependencies for the project
      - run: flutter pub get

      # Build the web app
      - run: flutter build web

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          channelId: live
          projectId: recipe-maker-9c7a0
