name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches:
      - main # Specify the branch you want the workflow to run on PRs

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies for Flutter and Firebase
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Explicitly ensure Flutter is in the PATH
      - name: Add Flutter to PATH
        run: echo "$HOME/flutter/bin" >> $GITHUB_PATH

      # Verify Flutter installation
      - name: Verify Flutter installation
        run: flutter --version

      # Build Flutter web app
      - name: Build Flutter web app
        run: flutter build web

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECIPE_MAKER_9C7A0 }}
          projectId: recipe-maker-9c7a0
